### PR TITLE
Switch theme

### LINKED ISSUE #27: Dark Mode Toggle
A toggle should be there which should switch the website into dark mode! I mean it's a boon for programmers!

### PR DESCRIPTION
**Pull request by Priya2123**

### CODE REVIEW

**Comment by jsparmani** [comment]
Fixes #27

**Comment by aniketbiswas21** [comment]
Great work @Priya2123 🚀

**Comment by aniketbiswas21** [comment]
@jsparmani  and @kush-daga Please check this out 😃

**Comment by kush-daga** [comment]
Looks great! Will do a detailed review later.. For now looks nice.

**Comment by aniketbiswas21** [comment]
@jsparmani The checks are failing again 😕

**Comment by jsparmani** [comment]
Hey, @Priya2123 extremely nice job 🚀 
Almost everything works perfect! Although a minor things still need to be corrected. Will request changes with the exact details

**Comment by jsparmani** [comment]
> @jsparmani The checks are failing again 😕

@aniketbiswas21 The code was pushed without proper pre-commit setup as the checks were failing locally. Pushing with the command `pre-commit run --all` again fixed this.

**Comment by Priya2123** [comment]
Thank you :smile:

**Review by jsparmani — CHANGES_REQUESTED** [review]
image
Found that the modals on events and projects page don't change on toggling dark mode. Everything else works like a charm!

Also, after closing the modal, the original card changes to something like this below. See, if this could be fixed
image

**Comment by kush-daga** [comment]
Great job @Priya2123

**Comment by kush-daga** [comment]
One more thing @Priya2123 @jsparmani Dont you guys think that the directory naming is a bit weird, the folder named "toggle" does not make that much sense, so probably could have some better naming for the same?
Probably could make it another issue, and add in for hacktober?

**Comment by animesh-007** [comment]
@Priya2123 Nice 👍 . Just a small suggestion on the switch.  What are your views on this type of switch [Link](https://codepen.io/maximakymenko/pen/mdbpeXm)? I think it will be cool to have something like this.

**Comment by jsparmani** [comment]
> One more thing @Priya2123 @jsparmani Dont you guys think that the directory naming is a bit weird, the folder named "toggle" does not make that much sense, so probably could have some better naming for the same?
> Probably could make it another issue, and add in for hacktober?

Agreed. Let's keep it for hactoberfest. @Priya2123 you can create an issue for the same with label Hactoberfest

**Comment by jsparmani** [comment]
> @Priya2123 Nice 👍 . Just a small suggestion on the switch. What are your views on this type of switch [Link](https://codepen.io/maximakymenko/pen/mdbpeXm)? I think it will be cool to have something like this.

Yeah, could be done. @Priya2123 check this out if it could be integrated without much changes to be made to the existing toggle switch.

**Comment by Priya2123** [comment]
@jsparmani  I have made the changes you requested. The switch would need some additional changes to implement the one @animesh-007 suggested and I'll make a separate pr for that.

**Comment by jsparmani** [comment]
Nice 🚀

**Comment by jsparmani** [comment]
@all-contributors please add @Priya2123 for design and code.

**Pull request merged**
