### PR TITLE
removed chatbot and fixed card focus bug

### LINKED ISSUE #255: Remove Chatbot
Over-engineered feature. Don't need it imo. @jsparmani your views?

### PR DESCRIPTION
**Pull request by aniketbiswas21**
Fixes #255, #271 and #262

### CODE REVIEW

**Comment by aniketbiswas21** [comment]
@jsparmani didn't remove the chatbot code, just removed the imports.

**Comment by jsparmani** [comment]
Hey, @aniketbiswas21 the changes done are correct, but there is something more do be done.
https://github.com/developer-student-club-thapar/officialWebsite/blob/master/public/chatbot.js
This file is also linked to the chatbot and is the main reason for the XSS vulnerability.
I suggest to remove all linking to the file as well done inside the `public` folder.
I have attached the exact link to the diff in the github issue for reference to all that has to be removed.

@aniketbiswas21 Edited this comment again, kindly check it out.

**Comment by aniketbiswas21** [comment]
Okay, I will remove this

**Comment by aniketbiswas21** [comment]
Done @jsparmani

**Comment by jsparmani** [comment]
@aniketbiswas21 Check line 33 in this file.
https://github.com/developer-student-club-thapar/officialWebsite/blob/master/public/index.html
That also has been removed otherwise will cause issues in the build.

**Review by jsparmani — CHANGES_REQUESTED** [review]
A few changes left to be done. Already commented regarding them.

**Review by jsparmani — APPROVED** [review]

**Comment by aniketbiswas21** [comment]
Done

**Pull request merged**
