### PR TITLE
Fixed issue #36

### PR DESCRIPTION
**Pull request by aniketbiswas21**
Added Hover Effects to the buttons on Home page.

### CODE REVIEW

**Comment by jsparmani** [comment]
@aniketbiswas21 Thanks for the contribution!

**Comment by kush-daga** [comment]
@aniketbiswas21 Good changes! It looks good, however, i feel we can still improve the button animations, will have to think of something, till then ill put this as the current animation! Thanks for the contribution.

**Comment by kush-daga** [comment]
Also @aniketbiswas21 next time try to use some better names, rather than button1 button2, etc. This is a good practice and would clean the code and make it look a lot better.

**Comment by aniketbiswas21** [comment]
@kush-daga Sure sir.

**Pull request merged**
