### PR TITLE
Meet the team image fix

### LINKED ISSUE #102: Fix Image of Meet the team
The image is stretched and that is not right, make it such that it is contained in the height and width while maintaining the aspect ratio. Shubhank Bhaiya's Image

### PR DESCRIPTION
**Pull request by kush-daga**
This fixes #102

### CODE REVIEW

**Comment by shubhank-saxena** [comment]
@kush-daga rebase the master on this branch! We have fixed the pycache issue!

**Comment by shubhank-saxena** [comment]
@jsparmani strange thing! There were no Travis builds triggered for this PR!

**Comment by jsparmani** [comment]
> @jsparmani strange thing! There were no Travis builds triggered for this PR!

Actually Travis doesn't get triggered if there are merge conflicts.

**Comment by shubhank-saxena** [comment]
> > @jsparmani strange thing! There were no Travis builds triggered for this PR!
> 
> Actually Travis doesn't get triggered if there are merge conflicts.

Oh shit! I forgot that! Sorry!

**Comment by jsparmani** [comment]
I am closing this one. The repo has significant structural changes after this PR was opened, so conflict handling is a bit tough.

**Pull request closed without merging**
