### PR TITLE
Added endpoints for user, project, achievements models

### PR DESCRIPTION
**Pull request by rdotjain**
- Added djangorestframework dependency
- Added serializers, endpoints for user, project, achievement models
- Added endpoints for Leads, Co-Leads

### CODE REVIEW

**Comment by sanchjain** [comment]
Great work!!

**Comment by Saurav-Shrivastav** [comment]
@all-contributors please add @rdotjain  for code 
@all-contributors please add @sanchjain  for maintenance

**Comment by Saurav-Shrivastav** [comment]
@all-contributors please add @rdotjain for code

**Comment by Saurav-Shrivastav** [comment]
@all-contributors please add @sanchjain  for maintenance

**Pull request merged**
