### PR TITLE
Podcast Models in Django Backend

### PR DESCRIPTION
**Pull request by AroraShreshth**
Python Logic in Models for Handling The Podcast Series Logic in DB

### CODE REVIEW

**Comment by jsparmani** [comment]
@AroraShreshth Travis tests are failing due to linting issues, please have a look into it.

**Comment by shubhank-saxena** [comment]
@jsparmani I am seeing a strange behavior here. Our .gitignore did have this, then why this PR having pychache being uploaded?
Also, if there are my caches, we need to remove them in a separate PR

**Comment by jsparmani** [comment]
> @jsparmani I am seeing a strange behavior here. Our .gitignore did have this, then why this PR having pychache being uploaded?
> Also, if there are my caches, we need to remove them in a separate PR

yeah, i see don't really know why isn't that ignored by git, would check it out

**Comment by shubhank-saxena** [comment]
@AroraShreshth rebase the master on this branch! We have fixed the pycache issue!

**Comment by AroraShreshth** [comment]
Done the neccesary changes

**Review by jsparmani — APPROVED** [review]

**Pull request merged**
