### PR TITLE
[WIP][Do Not Merge!] Dark Mode 

### LINKED ISSUE #27: Dark Mode Toggle
A toggle should be there which should switch the website into dark mode! I mean it's a boon for programmers!

### PR DESCRIPTION
**Pull request by RishabhK88**
This fixed #27 
Added Dark Mode for the website..There is a circle widget button in the bottom right hand side which can be clicked to change into dark mode and back. The cards in resources and events will have to be modified a little to adjust. Used the darkmode-js npm package.

### CODE REVIEW

**Comment by jsparmani** [comment]
@RishabhK88 We appreciate your effort towards the development of dark mode. So, there are a few things: 
1. We have been using [Material-UI](https://material-ui.com/) as our main frontend library. It has inbuilt dark mode option with the theme options, please explore that a bit, it already is compatible with the card components we have used.
2. Please use [pre-commit](https://pre-commit.com/) hooks so that there are no travis build failures for prettier for the modifications you have made. It ensures code quality and linting.

It would be great if you take this instructions forward and proceed with adding this functionality to the website.
I will be making a `CONTRIBUTION.md` file for this so that you have no issues setting up the development environment.
Let me know, if you are working further, I will assign this task to you.

**Comment by RishabhK88** [comment]
> Let me know, if you are working further, I will assign this task to you.
Yeah, i will try and figure out the material-ui dark mode. Thanks for the inputs

**Comment by jsparmani** [comment]
> > Let me know, if you are working further, I will assign this task to you.
> > Yeah, i will try and figure out the material-ui dark mode. Thanks for the inputs

Nice, `CONTRIBUTION.md` file has been updated for project setup directions. Also adhere to the pull request guidelines mentioned there.

**Comment by jsparmani** [comment]
@RishabhK88 Any progress with this?

**Comment by RishabhK88** [comment]
> @RishabhK88 Any progress with this?

I did try working on this... I tried the material ui... Dark mode... And it works... But the issue is with the toggle switch....Basically for it to work, I have to wrap the contents in a paper tag and then a theme provider tag... I find do this in index.js... It works... But when  I try placing the toggle switch....i can't place the toggle switch in index.js as it doesn't work there... And I cant figure out how to place it in the home page.. With all the props passing and events🤷🏻‍♂️.... Still trying to figure out a workaround for this

**Comment by jsparmani** [comment]
> > @RishabhK88 Any progress with this?
> 
> I did try working on this... I tried the material ui... Dark mode... And it works... But the issue is with the toggle switch....Basically for it to work, I have to wrap the contents in a paper tag and then a theme provider tag... I find do this in index.js... It works... But when I try placing the toggle switch....i can't place the toggle switch in index.js as it doesn't work there... And I cant figure out how to place it in the home page.. With all the props passing and events🤷🏻‍♂️.... Still trying to figure out a workaround for this

You can try using the Context API / Redux to globalize the state for dark theme, so you don't have to work with props. Also, you can push your code gradually to this PR so we can review it and provide suggestions if any. Intially you could just setup the toggling within the code and then we can somehow figure out how to bring that in the UI.

**Comment by RishabhK88** [comment]
>  You can try using the Context API / Redux to globalize the state for dark theme, so you don't have to work with props. Also, you can push your code gradually to this PR so we can review it and provide suggestions if any.

Okay.... Thanks

**Comment by jsparmani** [comment]
@RishabhK88 checkout  #52 , probably you could collaborate with @animesh-007 and complete the task.

**Pull request closed without merging**
