### PR TITLE
Revert "removed chatbot and fixed card focus bug"

### PR DESCRIPTION
**Pull request by jsparmani**
Reverts developer-student-club-thapar/officialWebsite#277

### CODE REVIEW

**Comment by jsparmani** [comment]
@aniketbiswas21 I need to revert the PR #277 because its breaking the frontend part of the website. Kindly analyze that branch to check what was going wrong. Will merge this PR as soon as checks pass

**Comment by aniketbiswas21** [comment]
@jsparmani  What's the problem? It is working fine in my system

**Comment by jsparmani** [comment]
> @jsparmani What's the problem? It is working fine in my system

I didn't check much. But https://dsctiet.tech was a blank page after merging this code.
You can checkout from the console errors.

**Comment by aniketbiswas21** [comment]
@jsparmani  I am not getting any :confused:

**Comment by jsparmani** [comment]
@aniketbiswas21 I see. Clearing cache and then reloading works for we. Keeping this PR as drafted, just in case we need to use it in future.

**Pull request closed without merging**
