### PR TITLE
Minor UI changes in Nav

### PR DESCRIPTION
**Pull request by pranjaljain0**
Added overflow: hidden to the toggle and fixed the navbar buttons on hover effect and placement.

### CODE REVIEW

**Comment by pranjaljain0** [comment]
I am not sure why the prebuilt is failing.
Please, someone, let me know what the problem is.
Thank you

**Comment by shubhank-saxena** [comment]
Hello @pranjaljain0 . Thank you for your contribution. Your linting tests for javascript are failing. Make sure you have followed theses steps - 
- Install pre-commit on your system `pip install pre-commit`
- Run pre-commit hook in your folder by navigating to it and run `pre-commit install`
- Run pre-commit hooks inside your folder `pre-commit run --all` and commit the changes that are done by the pre-commit
Hope this helps!

**Comment by pranjaljain0** [comment]
Thanks, @shubhank-saxena. will do the same.

**Comment by pranjaljain0** [comment]
@jsparmani it would be very grateful if you add the label hacktober accepted, Thank you.

**Pull request merged**
