### PR TITLE
#5 Created a form for Project Model

### PR DESCRIPTION
**Pull request by pranjalgupta29**
Templating to create a route to view projects is still remaining.

### CODE REVIEW

**Comment by jsparmani** [comment]
@pranjalgupta29 you don't need to close the PR

**Comment by jsparmani** [comment]
@pranjalgupta29 i guess url configuration for the view is missing. Please make those changes

**Review by jsparmani — CHANGES_REQUESTED** [review]
@pranjalgupta29 i guess url configuration for the view is missing. Please make those changes. Also, make the template file appropriately which is still missing

**Review by jsparmani — CHANGES_REQUESTED** [review]
@pranjalgupta29 i am getting a 404 error after submitting the form, can you please check that once. Also, the members input field should be a dropdown one.

**Comment by jsparmani** [comment]
@pranjalgupta29 Checkout this c6155562e19244971beb287b7a637bb3fd4e91be. Make the changes that are in urls.py accordingly. Your problem would be resolved

**Review by jsparmani — CHANGES_REQUESTED** [review]
@pranjalgupta29 Can you please post a short clip of the project form by filling out any dummy data.
Good work till now

**Comment by shubhank-saxena** [comment]
@pranjalgupta29 fix all the merge conflicts

**Comment by pranjalgupta29** [comment]
@shubhank-saxena I'll get to it asap

**Comment by shubhank-saxena** [comment]
@pranjalgupta29 unfortunately, we have migrated a lot of changes in repository. We will have to close this PR and devise a new workflow. After which, we will have to re-open this.
Thank you for your contributions!

**Comment by pranjalgupta29** [comment]
@shubhank-saxena okay. No issues.

**Pull request closed without merging**
