### PR TITLE
[WIP][Do Not Merge!]dark mode to projects page

### LINKED ISSUE #27: Dark Mode Toggle
A toggle should be there which should switch the website into dark mode! I mean it's a boon for programmers!

### PR DESCRIPTION
**Pull request by animesh-007**
Dark mode is applied to projects page with a switch to turn on/off. 
Need some suggestions on the switch and on this dark theme.
#27

### CODE REVIEW

**Comment by jsparmani** [comment]
Hi @animesh-007 . That's a great start. Let me review the changes and then you can work ahead.

**Comment by jsparmani** [comment]
Also, @animesh-007 I guess you need to follow the repo installation correctly and setup `pre-commit`. The Travis Builds are failing. Please check out the `CONTRIBUTION.md` file on steps to setup your environment.

**Comment by jsparmani** [comment]
@animesh-007 The approach is correct. There are a few things I would suggest
- [ ] The modal that gets opened after clicking _Learn More_ on projects card no more works correctly when dark mode is toggled
- [ ] The page switches back to default light mode on refreshing 
- [ ] It would be great if there's a website wide floating dark mode icon to toggle it at a more convenient place
- [ ] The UI of the toggle switch can be much better
- [ ] The Footer needs to switch to dark mode as well
- [ ] Navbar text color should change on dark mode toggle for better readability.
- [ ] Setup `Context API/Redux` (or anything better) for global dark mode state management.

Please confirm whether you are working further on this, so assign I to you. Further, push commits to this PR adhering to the above points.

**Comment by jsparmani** [comment]
You can checkout `ConfigProvider` in Ant Design to implement website wide dark mode. Also, you can setup `Context API/Redux` to maintain global state.

**Comment by animesh-007** [comment]
@jsparmani  Thanks for the suggestions.
I will be working on this issue.
Also I tried to follow contribution.md properly plus I have `pre-commit` in my environment still I don't know why test are failing

**Comment by jsparmani** [comment]
> @jsparmani Thanks for the suggestions.
> I will be working on this issue.
> Also I tried to follow contribution.md properly plus I have `pre-commit` in my environment still I don't know why test are failing

Okay, we shall check that. Just wanna know if you had run `pre-commit install` command or not, so it's easier to figure out if there's any issue

**Comment by animesh-007** [comment]
> pre-commit install

I think I forgot to do that😅

**Comment by jsparmani** [comment]
> > pre-commit install
> 
> I think I forgot to do that😅

Okay

**Comment by animesh-007** [comment]
Will it be okay if we add dark mode switch on the navbar?

**Comment by jsparmani** [comment]
> Will it be okay if we add dark mode switch on the navbar?
Yes

**Review by jsparmani — CHANGES_REQUESTED** [review]
Also, @animesh-007 it's better to write code in `.js` files and not create new `ts/tsx` files to keep the code base consistent.

**Comment by animesh-007** [comment]
> Also, @animesh-007 it's better to write code in `.js` files and not create new `ts/tsx` files to keep the code base consistent.

changed files to js.

**Comment by jsparmani** [comment]
> > Also, @animesh-007 it's better to write code in `.js` files and not create new `ts/tsx` files to keep the code base consistent.
> 
> changed files to js.

tick down the things that are done in original follow up comment

**Comment by animesh-007** [comment]
> @animesh-007 The approach is correct. There are a few things I would suggest
> 
> * [x]  The modal that gets opened after clicking _Learn More_ on projects card no more works correctly when dark mode is toggled
> * [x]  The page switches back to default light mode on refreshing
> * [ ]  It would be great if there's a website wide floating dark mode icon to toggle it at a more convenient place
> * [ ]  The UI of the toggle switch can be much better
> * [ ]  The Footer needs to switch to dark mode as well
> * [ ]  Navbar text color should change on dark mode toggle for better readability.
> * [ ]  Setup `Context API/Redux` (or anything better) for global dark mode state management.
> * [ ] Getting some errors on console.

**Comment by jsparmani** [comment]
@animesh-007 There a few errors uptil now

- The dark mode does not get on again once it's switched off
- There is some issue with dark mode on Projects page
- The toggler on navbar is too distinctive
- Also dark mode toggle isn't present in navbar in mobile UI
- Tests are still failing

**Comment by animesh-007** [comment]
> @animesh-007 There a few errors uptil now
> 
> * The dark mode does not get on again once it's switched off
> * There is some issue with dark mode on Projects page
> * The toggler on navbar is too distinctive
> * Also dark mode toggle isn't present in navbar in mobile UI
> * Tests are still failing

Okay, I will look into that.  It would be great if I get a helping hand.😅

**Comment by jsparmani** [comment]
> Okay, I will look into that. It would be great if I get a helping hand.😅

@animesh-007 You can collaborate with @RishabhK88 he was also working on the dark mode issue.

**Comment by jsparmani** [comment]
@animesh-007 @RishabhK88 any progress?

**Comment by animesh-007** [comment]
> @animesh-007 @RishabhK88 any progress?

Not yet as soon as I get any significant change I will push it.

**Comment by shubhank-saxena** [comment]
@animesh-007 I found out this article. Hope it helps!
https://dev.to/rohit1508/dark-mode-in-react-using-hooks-2dd1

**Pull request closed without merging**
