### PR TITLE
Resolve flake8 and prettier travis env to prevent test failures (#13)

### LINKED ISSUE #13: Fix environments to show consistent lint check across
Right now you see that Travis tests of linting is failing. But it must be passing local systems as my pre-commit is allwoing. 
Fix it

### PR DESCRIPTION
**Pull request by jsparmani**
@shubhank-saxena I have fixed the flake8 and prettier environments to avoid test failures. Looks like black `.toml` config file is still causing some issues.

### CODE REVIEW

**Comment by shubhank-saxena** [comment]
Wow! You are on the right track!! Keep it going forward! Just a hint - try to combine everything in setup.cfg because we still don't have peotry installed. So idk we won't be needing pyproject.toml.

**Comment by jsparmani** [comment]
Okay understood! Thanks for the help!

**Comment by shubhank-saxena** [comment]
> Okay understood! Thanks for the help!

Wait. Don't integrate them. Let me see a better workaround

**Comment by jsparmani** [comment]
> > Okay understood! Thanks for the help!
> 
> Wait. Don't integrate them. Let me see a better workaround

Okay, I am reverting back the changes

**Comment by shubhank-saxena** [comment]
Do one thing. 
pre-commit install in your repo once (as you have added new files). Run it now. I think it will fix everything

**Comment by shubhank-saxena** [comment]
Great Work @jsparmani

**Pull request merged**
