### PR TITLE
Click on nav-bar logo and name to go back to home page

### LINKED ISSUE #280: Click on nav-bar logo and name to go back to home page.
**Is your feature request related to a problem? Please describe.**
click on nav-bar logo and name to go back to home page. One should be able to go back `/#` when he clicks on the logo and name in the nav-bar, irrespective of the fact that he is on which page.

**Describe the solution you'd like**
a simple <a> tag could work but i would prefer using the react-router implementation.

### PR DESCRIPTION
**Pull request by sandeepbanoula**
Added Navigation to nav-bar logo and name to go back to the home page for both nav and mobile nav.
Guide me if needed changes
Fix For Navigation Issue #280

### CODE REVIEW

**Comment by shubhank-saxena** [comment]
Hello @sandeepbanoula . Thank you for your contribution. Your linting tests for javascript are failing. Make sure you have followed these steps -
- Install pre-commit on your system `pip install pre-commit`
- Run pre-commit hook in your folder by navigating to it and run `pre-commit install`
- Run pre-commit hooks inside your folder `pre-commit run --all` and commit the changes that are done by the pre-commit
Hope this helps!

**Comment by sandeepbanoula** [comment]
> Hello @sandeepbanoula . Thank you for your contribution. Your linting tests for javascript are failing. Make sure you have followed these steps -
> 
> * Install pre-commit on your system `pip install pre-commit`
> * Run pre-commit hook in your folder by navigating to it and run `pre-commit install`
> * Run pre-commit hooks inside your folder `pre-commit run --all` and commit the changes that are done by the pre-commit
>   Hope this helps!

Thanks, @shubhank-saxena  for helping me solving the linting errors(as it was my first commit). Regards, Sandeep

**Comment by shubhank-saxena** [comment]
Wohoo! :rocket: Congratulations @sandeepbanoula !

**Comment by shubhank-saxena** [comment]
Thank you for your contribution @sandeepbanoula . Happy Hacktoberfest! :heart:. Keep hacking!

**Pull request merged**
