### PR TITLE
added webp images

### LINKED ISSUE #30: Convert all png images to webp in home page for faster loading
We need to reduce time of load as well as compute resource usage!

### PR DESCRIPTION
**Pull request by animesh-007**
This fixes #30 
Converted png images to webp and changed import line in `Home.js`.

### CODE REVIEW

**Comment by jsparmani** [comment]
@animesh-007 Just converting the images won't really work. You either need to use a separate rendering tag for `webp` images or any other library for it.

**Review by jsparmani — CHANGES_REQUESTED** [review]
@animesh-007 Just converting out the images won't really work. A separate tag needs to be used for rendering `webp` images or any other good library could be used.

**Comment by animesh-007** [comment]
@jsparmani  Will this tag `<ImageWebp>`  help here?

**Comment by jsparmani** [comment]
> @jsparmani Will this tag `<ImageWebp>` help here?

Yupp

**Review by jsparmani — CHANGES_REQUESTED** [review]
@animesh-007 I think you have been working on the wrong file. The correct one is `HomeAlt.js`

**Comment by animesh-007** [comment]
> @animesh-007 Just converting out the images won't really work. A separate tag needs to be used for rendering `webp` images or any other good library could be used.

I was going through the HomeAlt.js file in that we have used Team.webp image with img tag so I tried to use same implementation over here also. I also saw we are using Thaparimg.jpg is it ok or we need to change it to webp format?
Is it okay?

**Comment by jsparmani** [comment]
@animesh-007 I guess the previous method you were using was correct, shift to the previous method for all webp images

**Comment by animesh-007** [comment]
> @animesh-007 I guess the previous method you were using was correct, shift to the previous method for all webp images

I tried to used the same approach now.

**Comment by jsparmani** [comment]
Nice 🚀

**Pull request merged**
