### PR TITLE
Solving Remove "Join us on Slack" Button #279

### PR DESCRIPTION
**Pull request by shivambhatia5432**
I tried solving the issue by removing the grid of join slack

### CODE REVIEW

**Review by jsparmani — CHANGES_REQUESTED** [review]
Hello @shivambhatia5432, the travis tests are failing. Please push the correct code to pass them

**Comment by shivambhatia5432** [comment]
How can I correct it? I have pushed the correct code I just removed the grid containing the slack button.

**Comment by jsparmani** [comment]
There are two errors-
1. The `yarn build` command is giving some errors, causing the build to fail.
2. The `pre-commit` setup isn't correct. Refer to steps in `CONTRIBUTING.md` for full setup.

**Comment by shivambhatia5432** [comment]
My bad this issue has been assigned to @crs2here.

**Pull request closed without merging**
