### PR TITLE
Homepage loader

### PR DESCRIPTION
**Pull request by ramyak-mehra**
This fixes #267 
A better approach could be used to count the times  onLoad callback fires. and suggestions @jsparmani  @aniketbiswas21 
Ps- Switch to slow 3g connection in the network tab to see the effect properly

### CODE REVIEW

**Comment by aniketbiswas21** [comment]
@ramyak-mehra Please look into the conflicts :face_with_head_bandage:

**Comment by ramyak-mehra** [comment]
> @ramyak-mehra Please look into the conflicts :face_with_head_bandage: 

@aniketbiswas21 I'll close this PR and create a new one just check my homepage loader commit

**Comment by animesh-007** [comment]
> > @ramyak-mehra Please look into the conflicts 🤕
> 
> @aniketbiswas21 I'll close this PR and create a new one just check my homepage loader commit

@ramyak-mehra I think you can solve this without closing PR. Fetch the master branch again and merge into this branch and you are good to go then IMO.😀

**Comment by ramyak-mehra** [comment]
@animesh-007 There are  just too many unnecessary  commits which are not required.

**Pull request closed without merging**
