### PR TITLE
changes to event card

### PR DESCRIPTION
**Pull request by NUMBART**

### CODE REVIEW

**Review by jsparmani — CHANGES_REQUESTED** [review]
@NUMBART The cards look good, but there is issue with the learn more button on the card with dark mode turned on.
image

Please fix this.

**Comment by NUMBART** [comment]
I just added the changes.

**Review by jsparmani — APPROVED** [review]
Nice 🚀

**Comment by NUMBART** [comment]
A separate issue I noticed is that click to the button propagates to the parent container as a result both events are triggered. Should I raise a issue for that? It is still there after the current PR

**Comment by jsparmani** [comment]
Sure. You can raise an issue for that. Let me know if you are working on it.

**Comment by NUMBART** [comment]
I am not aware of any fix. I will check online if I get a solution, will let you know. Also thank you, learned using material-ui in the process of making this PR.

**Comment by jsparmani** [comment]
Great.

**Pull request merged**
