### PR TITLE
Cleaned up the codebase

### PR DESCRIPTION
**Pull request by aniketbiswas21**

### CODE REVIEW

**Review by jsparmani — CHANGES_REQUESTED** [review]
Everything's working perfectly except the Footer on Team Page. It's height is very large
image

Please have a look into it!

**Comment by aniketbiswas21** [comment]
Yes, this was present in the previous version too. Not sure what's causing this. Will try to fix this ASAP.

**Comment by aniketbiswas21** [comment]
Done @jsparmani

**Review by jsparmani — APPROVED** [review]
Perfect

**Pull request merged**
