### PR TITLE
Removed all redundancies in code, push for hacktoberfest

### PR DESCRIPTION
**Pull request by oshiiii**
### Reduced redundancies in `src/pages/Events.js`

I have reduced code redundancies in the `src/pages/Events.js` for **hacktoberfest** <br />
I'll do the same for other components as well, once this PR gets merged.

### CODE REVIEW

**Comment by animesh-007** [comment]
Your linting tests are failing can you look into that. Try to follow these steps.
- Install pre-commit on your system `pip install pre-commit`.
- Run pre-commit hook in your folder by navigating to it and run `pre-commit install`.
- Run pre-commit hooks inside your folder `pre-commit run --all` and commit the changes that are done by the pre-commit.

Hope it helps you.😇

**Comment by oshiiii** [comment]
> Your linting tests are failing can you look into that. Try to follow these steps.
> 
> * Install pre-commit on your system `pip install pre-commit`.
> * Run pre-commit hook in your folder by navigating to it and run `pre-commit install`.
> * Run pre-commit hooks inside your folder `pre-commit run --all` and commit the changes that are done by the pre-commit.
> 
> Hope it helps you.😇

I ran the commands as above, it seems pre-commit ran into some issues while creating an environment for prettier, since I already have prettier installed on my machine, won't it be better to just have one `.prettierrc[.json | .js | .yaml]` file in our root directory, I find it a bit more resource exhausting to reinstall prettier in my `~/.git/hooks/` and also support it's environment by having a separate instance of node in that, while I already have them installed on my machine, is there not a way to make pre-commit use the system `$PATH` and use yarn instead of npm altogether...?

Screenshot 2020-10-04 at 14 33 43


I am on MacOS 10.15 Catalina β
node v14.11.0
npm v6.14.8
pre-commit v2.7.1

**Comment by shubhank-saxena** [comment]
> > Your linting tests are failing can you look into that. Try to follow these steps.
> > 
> > * Install pre-commit on your system `pip install pre-commit`.
> > * Run pre-commit hook in your folder by navigating to it and run `pre-commit install`.
> > * Run pre-commit hooks inside your folder `pre-commit run --all` and commit the changes that are done by the pre-commit.
> > 
> > Hope it helps you.innocent
> 
> I ran the commands as above, it seems pre-commit ran into some issues while creating an environment for prettier, since I already have prettier installed on my machine, won't it be better to just have one `.prettierrc[.json | .js | .yaml]` file in our root directory, I find it a bit more resource exhausting to reinstall prettier in my `~/.git/hooks/` and also support it's environment by having a separate instance of node in that, while I already have them installed on my machine, is there not a way to make pre-commit use the system `$PATH` and use yarn instead of npm altogether...?
> 
> Screenshot 2020-10-04 at 14 33 43
> 
> I am on MacOS 10.15 Catalina β
> node v14.11.0
> npm v6.14.8
> pre-commit v2.7.1

@oshiiii you can try cleaning your node cache. I think that will resolve the issues. As far as your doubt is concerned, git hooks don't collide with your system wide settings.

**Comment by jsparmani** [comment]
Changes look good to me. @oshiiii any success in setting up `pre-commit`?

**Comment by oshiiii** [comment]
> Changes look good to me. @oshiiii any success in setting up `pre-commit`?

No @jsparmani , I have tried to do everything, I had already taken this preliminary measures like cleaning npm cache, and in fact reinstalled node for the sake of it, but still no success on pre-commit.

**Comment by oshiiii** [comment]
I've opened an issue on `pre-commit`'s  repo, let's hope that things work out there.
https://github.com/pre-commit/pre-commit/issues/1631

**Comment by oshiiii** [comment]
Corrected everything, ran pre-commit, had to change the owner of the ~/.caches/pre-commit to current user.

**Comment by oshiiii** [comment]
Can my PR now be merged @animesh-007

**Comment by animesh-007** [comment]
@oshiiii Sure. As it is already approved, I will merge it. Happy Hacktoberfest!😃

**Comment by shubhank-saxena** [comment]
Thank you for your contribution @oshiiii ! Happy Hacktoberfest :heart: Keep hacking!

**Pull request merged**
